# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.api.policy_api import PolicyApi


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyApi()

    def tearDown(self) -> None:
        pass

    def test_system_policy_update(self) -> None:
        """Test case for system_policy_update

        Update top-level IAM policy
        """
        pass

    def test_system_policy_view(self) -> None:
        """Test case for system_policy_view

        Fetch top-level IAM policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
