# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.system_metric_name import SystemMetricName

class TestSystemMetricName(unittest.TestCase):
    """SystemMetricName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemMetricName(self):
        """Test SystemMetricName"""
        # inst = SystemMetricName()

if __name__ == '__main__':
    unittest.main()
