# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.switch_port_link_config import SwitchPortLinkConfig

class TestSwitchPortLinkConfig(unittest.TestCase):
    """SwitchPortLinkConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwitchPortLinkConfig:
        """Test SwitchPortLinkConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwitchPortLinkConfig`
        """
        model = SwitchPortLinkConfig()
        if include_optional:
            return SwitchPortLinkConfig(
                autoneg = True,
                fec = None,
                link_name = '',
                lldp_link_config_id = '',
                mtu = 0,
                port_settings_id = '',
                speed = None
            )
        else:
            return SwitchPortLinkConfig(
                autoneg = True,
                fec = None,
                link_name = '',
                mtu = 0,
                port_settings_id = '',
                speed = None,
        )
        """

    def testSwitchPortLinkConfig(self):
        """Test SwitchPortLinkConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
