# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.identity_type import IdentityType

class TestIdentityType(unittest.TestCase):
    """IdentityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityType(self):
        """Test IdentityType"""
        # inst = IdentityType()

if __name__ == '__main__':
    unittest.main()
