# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.datum_one_of18 import DatumOneOf18

class TestDatumOneOf18(unittest.TestCase):
    """DatumOneOf18 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatumOneOf18:
        """Test DatumOneOf18
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatumOneOf18`
        """
        model = DatumOneOf18()
        if include_optional:
            return DatumOneOf18(
                datum = oxide.models.histogramuint8.Histogramuint8(
                    bins = [
                        oxide.models.binuint8.Binuint8(
                            count = 0, 
                            range = null, )
                        ], 
                    max = 0, 
                    min = 0, 
                    n_samples = 0, 
                    p50 = null, 
                    p90 = null, 
                    p99 = null, 
                    squared_mean = 1.337, 
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sum_of_samples = 56, ),
                type = 'histogram_u8'
            )
        else:
            return DatumOneOf18(
                datum = oxide.models.histogramuint8.Histogramuint8(
                    bins = [
                        oxide.models.binuint8.Binuint8(
                            count = 0, 
                            range = null, )
                        ], 
                    max = 0, 
                    min = 0, 
                    n_samples = 0, 
                    p50 = null, 
                    p90 = null, 
                    p99 = null, 
                    squared_mean = 1.337, 
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sum_of_samples = 56, ),
                type = 'histogram_u8',
        )
        """

    def testDatumOneOf18(self):
        """Test DatumOneOf18"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
