# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.project_role_policy import ProjectRolePolicy

class TestProjectRolePolicy(unittest.TestCase):
    """ProjectRolePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectRolePolicy:
        """Test ProjectRolePolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectRolePolicy`
        """
        model = ProjectRolePolicy()
        if include_optional:
            return ProjectRolePolicy(
                role_assignments = [
                    oxide.models.project_role_role_assignment.ProjectRoleRoleAssignment(
                        identity_id = '', 
                        identity_type = 'silo_user', 
                        role_name = 'admin', )
                    ]
            )
        else:
            return ProjectRolePolicy(
                role_assignments = [
                    oxide.models.project_role_role_assignment.ProjectRoleRoleAssignment(
                        identity_id = '', 
                        identity_type = 'silo_user', 
                        role_name = 'admin', )
                    ],
        )
        """

    def testProjectRolePolicy(self):
        """Test ProjectRolePolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
