# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.ip_pool_silo_link import IpPoolSiloLink

class TestIpPoolSiloLink(unittest.TestCase):
    """IpPoolSiloLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IpPoolSiloLink:
        """Test IpPoolSiloLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IpPoolSiloLink`
        """
        model = IpPoolSiloLink()
        if include_optional:
            return IpPoolSiloLink(
                ip_pool_id = '',
                is_default = True,
                silo_id = ''
            )
        else:
            return IpPoolSiloLink(
                ip_pool_id = '',
                is_default = True,
                silo_id = '',
        )
        """

    def testIpPoolSiloLink(self):
        """Test IpPoolSiloLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
