# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.route_destination_one_of3 import RouteDestinationOneOf3

class TestRouteDestinationOneOf3(unittest.TestCase):
    """RouteDestinationOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RouteDestinationOneOf3:
        """Test RouteDestinationOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RouteDestinationOneOf3`
        """
        model = RouteDestinationOneOf3()
        if include_optional:
            return RouteDestinationOneOf3(
                type = 'subnet',
                value = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return RouteDestinationOneOf3(
                type = 'subnet',
                value = ERROR_TO_EXAMPLE_VALUE,
        )
        """

    def testRouteDestinationOneOf3(self):
        """Test RouteDestinationOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
