# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.api.snapshots_api import SnapshotsApi


class TestSnapshotsApi(unittest.TestCase):
    """SnapshotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnapshotsApi()

    def tearDown(self) -> None:
        pass

    def test_snapshot_create(self) -> None:
        """Test case for snapshot_create

        Create snapshot
        """
        pass

    def test_snapshot_delete(self) -> None:
        """Test case for snapshot_delete

        Delete snapshot
        """
        pass

    def test_snapshot_list(self) -> None:
        """Test case for snapshot_list

        List snapshots
        """
        pass

    def test_snapshot_view(self) -> None:
        """Test case for snapshot_view

        Fetch snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
