# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.ipv4_range import Ipv4Range

class TestIpv4Range(unittest.TestCase):
    """Ipv4Range unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ipv4Range:
        """Test Ipv4Range
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ipv4Range`
        """
        model = Ipv4Range()
        if include_optional:
            return Ipv4Range(
                first = '',
                last = ''
            )
        else:
            return Ipv4Range(
                first = '',
                last = '',
        )
        """

    def testIpv4Range(self):
        """Test Ipv4Range"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
