# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.import_export_policy_one_of import ImportExportPolicyOneOf

class TestImportExportPolicyOneOf(unittest.TestCase):
    """ImportExportPolicyOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportExportPolicyOneOf:
        """Test ImportExportPolicyOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportExportPolicyOneOf`
        """
        model = ImportExportPolicyOneOf()
        if include_optional:
            return ImportExportPolicyOneOf(
                type = 'no_filtering'
            )
        else:
            return ImportExportPolicyOneOf(
                type = 'no_filtering',
        )
        """

    def testImportExportPolicyOneOf(self):
        """Test ImportExportPolicyOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
