# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.switch_port_config import SwitchPortConfig

class TestSwitchPortConfig(unittest.TestCase):
    """SwitchPortConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwitchPortConfig:
        """Test SwitchPortConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwitchPortConfig`
        """
        model = SwitchPortConfig()
        if include_optional:
            return SwitchPortConfig(
                geometry = None,
                port_settings_id = ''
            )
        else:
            return SwitchPortConfig(
                geometry = None,
                port_settings_id = '',
        )
        """

    def testSwitchPortConfig(self):
        """Test SwitchPortConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
