# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.datum_one_of3 import DatumOneOf3

class TestDatumOneOf3(unittest.TestCase):
    """DatumOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatumOneOf3:
        """Test DatumOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatumOneOf3`
        """
        model = DatumOneOf3()
        if include_optional:
            return DatumOneOf3(
                datum = 56,
                type = 'i16'
            )
        else:
            return DatumOneOf3(
                datum = 56,
                type = 'i16',
        )
        """

    def testDatumOneOf3(self):
        """Test DatumOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
