# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.silo_role import SiloRole

class TestSiloRole(unittest.TestCase):
    """SiloRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiloRole(self):
        """Test SiloRole"""
        # inst = SiloRole()

if __name__ == '__main__':
    unittest.main()
