# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.user_password_one_of1 import UserPasswordOneOf1

class TestUserPasswordOneOf1(unittest.TestCase):
    """UserPasswordOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPasswordOneOf1:
        """Test UserPasswordOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPasswordOneOf1`
        """
        model = UserPasswordOneOf1()
        if include_optional:
            return UserPasswordOneOf1(
                mode = 'login_disallowed'
            )
        else:
            return UserPasswordOneOf1(
                mode = 'login_disallowed',
        )
        """

    def testUserPasswordOneOf1(self):
        """Test UserPasswordOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
