# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.datum_one_of11 import DatumOneOf11

class TestDatumOneOf11(unittest.TestCase):
    """DatumOneOf11 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatumOneOf11:
        """Test DatumOneOf11
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatumOneOf11`
        """
        model = DatumOneOf11()
        if include_optional:
            return DatumOneOf11(
                datum = '',
                type = 'string'
            )
        else:
            return DatumOneOf11(
                datum = '',
                type = 'string',
        )
        """

    def testDatumOneOf11(self):
        """Test DatumOneOf11"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
