# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.switch_interface_kind import SwitchInterfaceKind

class TestSwitchInterfaceKind(unittest.TestCase):
    """SwitchInterfaceKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwitchInterfaceKind:
        """Test SwitchInterfaceKind
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwitchInterfaceKind`
        """
        model = SwitchInterfaceKind()
        if include_optional:
            return SwitchInterfaceKind(
                type = 'primary',
                vid = 0
            )
        else:
            return SwitchInterfaceKind(
                type = 'primary',
                vid = 0,
        )
        """

    def testSwitchInterfaceKind(self):
        """Test SwitchInterfaceKind"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
