# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.vpc_firewall_rule_protocol import VpcFirewallRuleProtocol

class TestVpcFirewallRuleProtocol(unittest.TestCase):
    """VpcFirewallRuleProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpcFirewallRuleProtocol(self):
        """Test VpcFirewallRuleProtocol"""
        # inst = VpcFirewallRuleProtocol()

if __name__ == '__main__':
    unittest.main()
