# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.bin_rangeint8_one_of1 import BinRangeint8OneOf1

class TestBinRangeint8OneOf1(unittest.TestCase):
    """BinRangeint8OneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BinRangeint8OneOf1:
        """Test BinRangeint8OneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BinRangeint8OneOf1`
        """
        model = BinRangeint8OneOf1()
        if include_optional:
            return BinRangeint8OneOf1(
                end = 56,
                start = 56,
                type = 'range'
            )
        else:
            return BinRangeint8OneOf1(
                end = 56,
                start = 56,
                type = 'range',
        )
        """

    def testBinRangeint8OneOf1(self):
        """Test BinRangeint8OneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
