# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.disk_source_one_of3 import DiskSourceOneOf3

class TestDiskSourceOneOf3(unittest.TestCase):
    """DiskSourceOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiskSourceOneOf3:
        """Test DiskSourceOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiskSourceOneOf3`
        """
        model = DiskSourceOneOf3()
        if include_optional:
            return DiskSourceOneOf3(
                block_size = 512,
                type = 'importing_blocks'
            )
        else:
            return DiskSourceOneOf3(
                block_size = 512,
                type = 'importing_blocks',
        )
        """

    def testDiskSourceOneOf3(self):
        """Test DiskSourceOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
