# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.field_type import FieldType

class TestFieldType(unittest.TestCase):
    """FieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldType(self):
        """Test FieldType"""
        # inst = FieldType()

if __name__ == '__main__':
    unittest.main()
