# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.api.system_ip_pools_api import SystemIpPoolsApi


class TestSystemIpPoolsApi(unittest.TestCase):
    """SystemIpPoolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemIpPoolsApi()

    def tearDown(self) -> None:
        pass

    def test_ip_pool_create(self) -> None:
        """Test case for ip_pool_create

        Create IP pool
        """
        pass

    def test_ip_pool_delete(self) -> None:
        """Test case for ip_pool_delete

        Delete IP pool
        """
        pass

    def test_ip_pool_list(self) -> None:
        """Test case for ip_pool_list

        List IP pools
        """
        pass

    def test_ip_pool_range_add(self) -> None:
        """Test case for ip_pool_range_add

        Add range to IP pool
        """
        pass

    def test_ip_pool_range_list(self) -> None:
        """Test case for ip_pool_range_list

        List ranges for IP pool
        """
        pass

    def test_ip_pool_range_remove(self) -> None:
        """Test case for ip_pool_range_remove

        Remove range from IP pool
        """
        pass

    def test_ip_pool_service_range_add(self) -> None:
        """Test case for ip_pool_service_range_add

        Add IP range to Oxide service pool
        """
        pass

    def test_ip_pool_service_range_list(self) -> None:
        """Test case for ip_pool_service_range_list

        List IP ranges for the Oxide service pool
        """
        pass

    def test_ip_pool_service_range_remove(self) -> None:
        """Test case for ip_pool_service_range_remove

        Remove IP range from Oxide service pool
        """
        pass

    def test_ip_pool_service_view(self) -> None:
        """Test case for ip_pool_service_view

        Fetch Oxide service IP pool
        """
        pass

    def test_ip_pool_silo_link(self) -> None:
        """Test case for ip_pool_silo_link

        Link IP pool to silo
        """
        pass

    def test_ip_pool_silo_list(self) -> None:
        """Test case for ip_pool_silo_list

        List IP pool's linked silos
        """
        pass

    def test_ip_pool_silo_unlink(self) -> None:
        """Test case for ip_pool_silo_unlink

        Unlink IP pool from silo
        """
        pass

    def test_ip_pool_silo_update(self) -> None:
        """Test case for ip_pool_silo_update

        Make IP pool default for silo
        """
        pass

    def test_ip_pool_update(self) -> None:
        """Test case for ip_pool_update

        Update IP pool
        """
        pass

    def test_ip_pool_utilization_view(self) -> None:
        """Test case for ip_pool_utilization_view

        Fetch IP pool utilization
        """
        pass

    def test_ip_pool_view(self) -> None:
        """Test case for ip_pool_view

        Fetch IP pool
        """
        pass


if __name__ == '__main__':
    unittest.main()
