# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.bin_rangeint64_one_of import BinRangeint64OneOf

class TestBinRangeint64OneOf(unittest.TestCase):
    """BinRangeint64OneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BinRangeint64OneOf:
        """Test BinRangeint64OneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BinRangeint64OneOf`
        """
        model = BinRangeint64OneOf()
        if include_optional:
            return BinRangeint64OneOf(
                end = 56,
                type = 'range_to'
            )
        else:
            return BinRangeint64OneOf(
                end = 56,
                type = 'range_to',
        )
        """

    def testBinRangeint64OneOf(self):
        """Test BinRangeint64OneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
