# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.vpc_firewall_rule import VpcFirewallRule

class TestVpcFirewallRule(unittest.TestCase):
    """VpcFirewallRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VpcFirewallRule:
        """Test VpcFirewallRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VpcFirewallRule`
        """
        model = VpcFirewallRule()
        if include_optional:
            return VpcFirewallRule(
                action = 'allow',
                description = '',
                direction = 'inbound',
                filters = oxide.models.vpc_firewall_rule_filter.VpcFirewallRuleFilter(
                    hosts = [
                        null
                        ], 
                    ports = [
                        '22'
                        ], 
                    protocols = [
                        'TCP'
                        ], ),
                id = '',
                name = ERROR_TO_EXAMPLE_VALUE,
                priority = 0,
                status = 'disabled',
                targets = [
                    null
                    ],
                time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                vpc_id = ''
            )
        else:
            return VpcFirewallRule(
                action = 'allow',
                description = '',
                direction = 'inbound',
                filters = oxide.models.vpc_firewall_rule_filter.VpcFirewallRuleFilter(
                    hosts = [
                        null
                        ], 
                    ports = [
                        '22'
                        ], 
                    protocols = [
                        'TCP'
                        ], ),
                id = '',
                name = ERROR_TO_EXAMPLE_VALUE,
                priority = 0,
                status = 'disabled',
                targets = [
                    null
                    ],
                time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                vpc_id = '',
        )
        """

    def testVpcFirewallRule(self):
        """Test VpcFirewallRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
