# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.vpc_firewall_rule_update import VpcFirewallRuleUpdate

class TestVpcFirewallRuleUpdate(unittest.TestCase):
    """VpcFirewallRuleUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VpcFirewallRuleUpdate:
        """Test VpcFirewallRuleUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VpcFirewallRuleUpdate`
        """
        model = VpcFirewallRuleUpdate()
        if include_optional:
            return VpcFirewallRuleUpdate(
                action = 'allow',
                description = '',
                direction = 'inbound',
                filters = oxide.models.vpc_firewall_rule_filter.VpcFirewallRuleFilter(
                    hosts = [
                        null
                        ], 
                    ports = [
                        '22'
                        ], 
                    protocols = [
                        'TCP'
                        ], ),
                name = ERROR_TO_EXAMPLE_VALUE,
                priority = 0,
                status = 'disabled',
                targets = [
                    null
                    ]
            )
        else:
            return VpcFirewallRuleUpdate(
                action = 'allow',
                description = '',
                direction = 'inbound',
                filters = oxide.models.vpc_firewall_rule_filter.VpcFirewallRuleFilter(
                    hosts = [
                        null
                        ], 
                    ports = [
                        '22'
                        ], 
                    protocols = [
                        'TCP'
                        ], ),
                name = ERROR_TO_EXAMPLE_VALUE,
                priority = 0,
                status = 'disabled',
                targets = [
                    null
                    ],
        )
        """

    def testVpcFirewallRuleUpdate(self):
        """Test VpcFirewallRuleUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
