# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.fleet_role import FleetRole

class TestFleetRole(unittest.TestCase):
    """FleetRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFleetRole(self):
        """Test FleetRole"""
        # inst = FleetRole()

if __name__ == '__main__':
    unittest.main()
