# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from oxide.models.datum_one_of7 import DatumOneOf7

class TestDatumOneOf7(unittest.TestCase):
    """DatumOneOf7 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatumOneOf7:
        """Test DatumOneOf7
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatumOneOf7`
        """
        model = DatumOneOf7()
        if include_optional:
            return DatumOneOf7(
                datum = 56,
                type = 'i64'
            )
        else:
            return DatumOneOf7(
                datum = 56,
                type = 'i64',
        )
        """

    def testDatumOneOf7(self):
        """Test DatumOneOf7"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
