# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from oxide.models.name_or_id import NameOrId
from typing import Optional, Set
from typing_extensions import Self

class LoopbackAddressCreate(BaseModel):
    """
    Parameters for creating a loopback address on a particular rack switch.
    """ # noqa: E501
    address: StrictStr = Field(description="The address to create.")
    address_lot: NameOrId = Field(description="The name or id of the address lot this loopback address will pull an address from.")
    anycast: StrictBool = Field(description="Address is an anycast address. This allows the address to be assigned to multiple locations simultaneously.")
    mask: Annotated[int, Field(strict=True, ge=0)] = Field(description="The subnet mask to use for the address.")
    rack_id: StrictStr = Field(description="The containing the switch this loopback address will be configured on.")
    switch_location: Annotated[str, Field(min_length=1, strict=True, max_length=63)] = Field(description="The location of the switch within the rack this loopback address will be configured on.")
    __properties: ClassVar[List[str]] = ["address", "address_lot", "anycast", "mask", "rack_id", "switch_location"]

    @field_validator('switch_location')
    def switch_location_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoopbackAddressCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address_lot
        if self.address_lot:
            _dict['address_lot'] = self.address_lot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoopbackAddressCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "address_lot": NameOrId.from_dict(obj["address_lot"]) if obj.get("address_lot") is not None else None,
            "anycast": obj.get("anycast"),
            "mask": obj.get("mask"),
            "rack_id": obj.get("rack_id"),
            "switch_location": obj.get("switch_location")
        })
        return _obj


