# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from oxide.models.network_interface_kind_one_of import NetworkInterfaceKindOneOf
from oxide.models.network_interface_kind_one_of1 import NetworkInterfaceKindOneOf1
from oxide.models.network_interface_kind_one_of2 import NetworkInterfaceKindOneOf2
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

NETWORKINTERFACEKIND_ONE_OF_SCHEMAS = ["NetworkInterfaceKindOneOf", "NetworkInterfaceKindOneOf1", "NetworkInterfaceKindOneOf2"]

class NetworkInterfaceKind(BaseModel):
    """
    The type of network interface
    """
    # data type: NetworkInterfaceKindOneOf
    oneof_schema_1_validator: Optional[NetworkInterfaceKindOneOf] = None
    # data type: NetworkInterfaceKindOneOf1
    oneof_schema_2_validator: Optional[NetworkInterfaceKindOneOf1] = None
    # data type: NetworkInterfaceKindOneOf2
    oneof_schema_3_validator: Optional[NetworkInterfaceKindOneOf2] = None
    actual_instance: Optional[Union[NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2]] = None
    one_of_schemas: Set[str] = { "NetworkInterfaceKindOneOf", "NetworkInterfaceKindOneOf1", "NetworkInterfaceKindOneOf2" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = NetworkInterfaceKind.model_construct()
        error_messages = []
        match = 0
        # validate data type: NetworkInterfaceKindOneOf
        if not isinstance(v, NetworkInterfaceKindOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NetworkInterfaceKindOneOf`")
        else:
            match += 1
        # validate data type: NetworkInterfaceKindOneOf1
        if not isinstance(v, NetworkInterfaceKindOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NetworkInterfaceKindOneOf1`")
        else:
            match += 1
        # validate data type: NetworkInterfaceKindOneOf2
        if not isinstance(v, NetworkInterfaceKindOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NetworkInterfaceKindOneOf2`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NetworkInterfaceKind with oneOf schemas: NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NetworkInterfaceKind with oneOf schemas: NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into NetworkInterfaceKindOneOf
        try:
            instance.actual_instance = NetworkInterfaceKindOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NetworkInterfaceKindOneOf1
        try:
            instance.actual_instance = NetworkInterfaceKindOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NetworkInterfaceKindOneOf2
        try:
            instance.actual_instance = NetworkInterfaceKindOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NetworkInterfaceKind with oneOf schemas: NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NetworkInterfaceKind with oneOf schemas: NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NetworkInterfaceKindOneOf, NetworkInterfaceKindOneOf1, NetworkInterfaceKindOneOf2]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


