# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from oxide.models.route_destination import RouteDestination
from oxide.models.route_target import RouteTarget
from oxide.models.router_route_kind import RouterRouteKind
from typing import Optional, Set
from typing_extensions import Self

class RouterRoute(BaseModel):
    """
    A route defines a rule that governs where traffic should be sent based on its destination.
    """ # noqa: E501
    description: StrictStr = Field(description="human-readable free-form text about a resource")
    destination: RouteDestination = Field(description="Selects which traffic this routing rule will apply to.")
    id: StrictStr = Field(description="unique, immutable, system-controlled identifier for each resource")
    kind: RouterRouteKind = Field(description="Describes the kind of router. Set at creation. `read-only`")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=63)] = Field(description="unique, mutable, user-controlled identifier for each resource")
    target: RouteTarget = Field(description="The location that matched packets should be forwarded to.")
    time_created: datetime = Field(description="timestamp when this resource was created")
    time_modified: datetime = Field(description="timestamp when this resource was last modified")
    vpc_router_id: StrictStr = Field(description="The ID of the VPC Router to which the route belongs")
    __properties: ClassVar[List[str]] = ["description", "destination", "id", "kind", "name", "target", "time_created", "time_modified", "vpc_router_id"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouterRoute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of kind
        if self.kind:
            _dict['kind'] = self.kind.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouterRoute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "destination": RouteDestination.from_dict(obj["destination"]) if obj.get("destination") is not None else None,
            "id": obj.get("id"),
            "kind": RouterRouteKind.from_dict(obj["kind"]) if obj.get("kind") is not None else None,
            "name": obj.get("name"),
            "target": RouteTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "time_created": obj.get("time_created"),
            "time_modified": obj.get("time_modified"),
            "vpc_router_id": obj.get("vpc_router_id")
        })
        return _obj


