# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from oxide.models.der_encoded_key_pair import DerEncodedKeyPair
from oxide.models.idp_metadata_source import IdpMetadataSource
from typing import Optional, Set
from typing_extensions import Self

class SamlIdentityProviderCreate(BaseModel):
    """
    Create-time identity-related parameters
    """ # noqa: E501
    acs_url: StrictStr = Field(description="service provider endpoint where the response will be sent")
    description: StrictStr
    group_attribute_name: Optional[StrictStr] = Field(default=None, description="If set, SAML attributes with this name will be considered to denote a user's group membership, where the attribute value(s) should be a comma-separated list of group names.")
    idp_entity_id: StrictStr = Field(description="idp's entity id")
    idp_metadata_source: IdpMetadataSource = Field(description="the source of an identity provider metadata descriptor")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=63)] = Field(description="Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.")
    signing_keypair: Optional[DerEncodedKeyPair] = Field(default=None, description="request signing key pair")
    slo_url: StrictStr = Field(description="service provider endpoint where the idp should send log out requests")
    sp_client_id: StrictStr = Field(description="sp's client id")
    technical_contact_email: StrictStr = Field(description="customer's technical contact for saml configuration")
    __properties: ClassVar[List[str]] = ["acs_url", "description", "group_attribute_name", "idp_entity_id", "idp_metadata_source", "name", "signing_keypair", "slo_url", "sp_client_id", "technical_contact_email"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^(?![0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)^[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9]+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SamlIdentityProviderCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of idp_metadata_source
        if self.idp_metadata_source:
            _dict['idp_metadata_source'] = self.idp_metadata_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of signing_keypair
        if self.signing_keypair:
            _dict['signing_keypair'] = self.signing_keypair.to_dict()
        # set to None if group_attribute_name (nullable) is None
        # and model_fields_set contains the field
        if self.group_attribute_name is None and "group_attribute_name" in self.model_fields_set:
            _dict['group_attribute_name'] = None

        # set to None if signing_keypair (nullable) is None
        # and model_fields_set contains the field
        if self.signing_keypair is None and "signing_keypair" in self.model_fields_set:
            _dict['signing_keypair'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SamlIdentityProviderCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acs_url": obj.get("acs_url"),
            "description": obj.get("description"),
            "group_attribute_name": obj.get("group_attribute_name"),
            "idp_entity_id": obj.get("idp_entity_id"),
            "idp_metadata_source": IdpMetadataSource.from_dict(obj["idp_metadata_source"]) if obj.get("idp_metadata_source") is not None else None,
            "name": obj.get("name"),
            "signing_keypair": DerEncodedKeyPair.from_dict(obj["signing_keypair"]) if obj.get("signing_keypair") is not None else None,
            "slo_url": obj.get("slo_url"),
            "sp_client_id": obj.get("sp_client_id"),
            "technical_contact_email": obj.get("technical_contact_email")
        })
        return _obj


