# coding: utf-8

"""
    Oxide Region API

    API for interacting with the Oxide control plane

    The version of the OpenAPI document: 20240821.0
    Contact: api@oxide.computer
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from oxide.models.vpc_firewall_rule_target_one_of import VpcFirewallRuleTargetOneOf
from oxide.models.vpc_firewall_rule_target_one_of1 import VpcFirewallRuleTargetOneOf1
from oxide.models.vpc_firewall_rule_target_one_of2 import VpcFirewallRuleTargetOneOf2
from oxide.models.vpc_firewall_rule_target_one_of3 import VpcFirewallRuleTargetOneOf3
from oxide.models.vpc_firewall_rule_target_one_of4 import VpcFirewallRuleTargetOneOf4
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

VPCFIREWALLRULETARGET_ONE_OF_SCHEMAS = ["VpcFirewallRuleTargetOneOf", "VpcFirewallRuleTargetOneOf1", "VpcFirewallRuleTargetOneOf2", "VpcFirewallRuleTargetOneOf3", "VpcFirewallRuleTargetOneOf4"]

class VpcFirewallRuleTarget(BaseModel):
    """
    A `VpcFirewallRuleTarget` is used to specify the set of instances to which a firewall rule applies. You can target instances directly by name, or specify a VPC, VPC subnet, IP, or IP subnet, which will apply the rule to traffic going to all matching instances. Targets are additive: the rule applies to instances matching ANY target.
    """
    # data type: VpcFirewallRuleTargetOneOf
    oneof_schema_1_validator: Optional[VpcFirewallRuleTargetOneOf] = None
    # data type: VpcFirewallRuleTargetOneOf1
    oneof_schema_2_validator: Optional[VpcFirewallRuleTargetOneOf1] = None
    # data type: VpcFirewallRuleTargetOneOf2
    oneof_schema_3_validator: Optional[VpcFirewallRuleTargetOneOf2] = None
    # data type: VpcFirewallRuleTargetOneOf3
    oneof_schema_4_validator: Optional[VpcFirewallRuleTargetOneOf3] = None
    # data type: VpcFirewallRuleTargetOneOf4
    oneof_schema_5_validator: Optional[VpcFirewallRuleTargetOneOf4] = None
    actual_instance: Optional[Union[VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4]] = None
    one_of_schemas: Set[str] = { "VpcFirewallRuleTargetOneOf", "VpcFirewallRuleTargetOneOf1", "VpcFirewallRuleTargetOneOf2", "VpcFirewallRuleTargetOneOf3", "VpcFirewallRuleTargetOneOf4" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = VpcFirewallRuleTarget.model_construct()
        error_messages = []
        match = 0
        # validate data type: VpcFirewallRuleTargetOneOf
        if not isinstance(v, VpcFirewallRuleTargetOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VpcFirewallRuleTargetOneOf`")
        else:
            match += 1
        # validate data type: VpcFirewallRuleTargetOneOf1
        if not isinstance(v, VpcFirewallRuleTargetOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VpcFirewallRuleTargetOneOf1`")
        else:
            match += 1
        # validate data type: VpcFirewallRuleTargetOneOf2
        if not isinstance(v, VpcFirewallRuleTargetOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VpcFirewallRuleTargetOneOf2`")
        else:
            match += 1
        # validate data type: VpcFirewallRuleTargetOneOf3
        if not isinstance(v, VpcFirewallRuleTargetOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VpcFirewallRuleTargetOneOf3`")
        else:
            match += 1
        # validate data type: VpcFirewallRuleTargetOneOf4
        if not isinstance(v, VpcFirewallRuleTargetOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VpcFirewallRuleTargetOneOf4`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in VpcFirewallRuleTarget with oneOf schemas: VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in VpcFirewallRuleTarget with oneOf schemas: VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into VpcFirewallRuleTargetOneOf
        try:
            instance.actual_instance = VpcFirewallRuleTargetOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VpcFirewallRuleTargetOneOf1
        try:
            instance.actual_instance = VpcFirewallRuleTargetOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VpcFirewallRuleTargetOneOf2
        try:
            instance.actual_instance = VpcFirewallRuleTargetOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VpcFirewallRuleTargetOneOf3
        try:
            instance.actual_instance = VpcFirewallRuleTargetOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VpcFirewallRuleTargetOneOf4
        try:
            instance.actual_instance = VpcFirewallRuleTargetOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into VpcFirewallRuleTarget with oneOf schemas: VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into VpcFirewallRuleTarget with oneOf schemas: VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], VpcFirewallRuleTargetOneOf, VpcFirewallRuleTargetOneOf1, VpcFirewallRuleTargetOneOf2, VpcFirewallRuleTargetOneOf3, VpcFirewallRuleTargetOneOf4]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


